### PR TITLE
fix: query for qualified/unqualified forms in revocation notification

### LINKED ISSUE #1864: Issue with revoking AnonCreds credentials
After upgrading from AFJ 0.4.2 to Credo 0.5.2 revocation seems to have stopped working with the credentials we use (anoncreds). The failure happens in `@credo-ts/packages/core/src/modules/credentials/protocol/revocation-notification/services/RevocationNotificationService.ts` in `processRevocationNotification` method when `this.credentialRepository.getSingleByQuery` is called. That method is throwing an error because `findSingleByQuery` is returning null in `@credo-ts/packages/core/src/storage/Repository.ts` ie. it didn't find any records.

Here is one of the sample queries that is getting this error, it looks normal to me but let me know if you notice anything wrong. 

```
{
  "anonCredsCredentialRevocationId": "3",
  "anonCredsRevocationRegistryId": "J6LCm5Edi9Mi3ASZCqNC1A:4:J6LCm5Edi9Mi3ASZCqNC1A:3:CL:109799:dev-attestation:CL_ACCUM:a76612f2-d80e-4bfb-8739-0c468c728d6a",
  "connectionId": "aa602260-631f-40f3-8442-2194da060c1a"
}
```

Might be worth mentioning that this still happens if the credentials are new, ie. they were both issued and then revoked after the upgrade to 0.5.2. (not just for old credentials from before 0.5.2 getting revoked)

Relevant dep versions (this occurs in Bifold / BC Wallet):
```
"@credo-ts/anoncreds": "0.5.2",
"@credo-ts/askar": "0.5.2",
"@credo-ts/core": "0.5.2",
"@credo-ts/drpc": "0.5.2",
"@credo-ts/indy-sdk-to-askar-migration": "0.5.2",
"@credo-ts/indy-vdr": "0.5.2",
"@credo-ts/push-notifications": "0.7.0",
"@credo-ts/question-answer": "0.5.2",
"@credo-ts/react-hooks": "^0.6.0",
"@credo-ts/react-native": "0.5.2",
"@hyperledger/anoncreds-react-native": "0.2.1",
"@hyperledger/aries-askar-react-native": "0.2.1",
"@hyperledger/indy-vdr-react-native": "0.2.2",
```

### PR DESCRIPTION
**Pull request by genaris**
Now querying in both qualified and unqualified forms for revocation registry id. Didn't add any specific test for this yet.

@bryce-mcmath it would be great if by chance you can verify that this properly solves your issue with legacy indy credentals.

Fixes #1864

### CODE REVIEW

**Comment by wadeking98** [comment]
could we also do this for credentials and proofs?

**Comment by bryce-mcmath** [comment]
Still getting no records with the updated query. Here's what the query ends up looking like:
```
"$or": [
    {
      "anonCredsRevocationRegistryId": "M6dhuFj5UwbhWkSLmvYSPc:4:M6dhuFj5UwbhWkSLmvYSPc:3:CL:612088:student_card:CL_ACCUM:5f6b196c-2051-4c30-92e1-e22af703ba8f",
      "anonCredsCredentialRevocationId": "14",
      "connectionId": "c8b60a89-4849-4697-9d8b-326e1f1ddc5c"
    },
    {
      "anonCredsRevocationRegistryId": "M6dhuFj5UwbhWkSLmvYSPc:4:M6dhuFj5UwbhWkSLmvYSPc:3:CL:612088:student_card:CL_ACCUM:5f6b196c-2051-4c30-92e1-e22af703ba8f",
      "anonCredsUnqualifiedRevocationRegistryId": "14",
      "connectionId": "c8b60a89-4849-4697-9d8b-326e1f1ddc5c"
    }
  ]
```

I thought maybe the values passed were incorrect so I tried switching them, but still retrieved no records. Here's what that query looked like:
```
"$or": [
    {
      "anonCredsRevocationRegistryId": "M6dhuFj5UwbhWkSLmvYSPc:4:M6dhuFj5UwbhWkSLmvYSPc:3:CL:612088:student_card:CL_ACCUM:5f6b196c-2051-4c30-92e1-e22af703ba8f",
      "anonCredsCredentialRevocationId": "13",
      "connectionId": "90da9419-b550-4616-b087-0e48efd78b0d"
    },
    {
      "anonCredsUnqualifiedRevocationRegistryId": "M6dhuFj5UwbhWkSLmvYSPc:4:M6dhuFj5UwbhWkSLmvYSPc:3:CL:612088:student_card:CL_ACCUM:5f6b196c-2051-4c30-92e1-e22af703ba8f",
      "anonCredsCredentialRevocationId": "13",
      "connectionId": "90da9419-b550-4616-b087-0e48efd78b0d"
    }
  ]
```

Not sure if I mentioned this already but it appears to be using the 'V1' revocation notification process, if that's helpful. Let me know what further info I could provide that might help.

**Comment by bryce-mcmath** [comment]
@TimoGlastra please let me know if you see anything odd about the above that could cause no records to be found

**Comment by genaris** [comment]
> Still getting no records with the updated query. Here's what the query ends up looking like:
> 
> ```
> "$or": [
>     {
>       "anonCredsRevocationRegistryId": "M6dhuFj5UwbhWkSLmvYSPc:4:M6dhuFj5UwbhWkSLmvYSPc:3:CL:612088:student_card:CL_ACCUM:5f6b196c-2051-4c30-92e1-e22af703ba8f",
>       "anonCredsCredentialRevocationId": "14",
>       "connectionId": "c8b60a89-4849-4697-9d8b-326e1f1ddc5c"
>     },
>     {
>       "anonCredsRevocationRegistryId": "M6dhuFj5UwbhWkSLmvYSPc:4:M6dhuFj5UwbhWkSLmvYSPc:3:CL:612088:student_card:CL_ACCUM:5f6b196c-2051-4c30-92e1-e22af703ba8f",
>       "anonCredsUnqualifiedRevocationRegistryId": "14",
>       "connectionId": "c8b60a89-4849-4697-9d8b-326e1f1ddc5c"
>     }
>   ]
> ```
> 
> I thought maybe the values passed were incorrect so I tried switching them, but still retrieved no records. Here's what that query looked like:
> 
> ```
> "$or": [
>     {
>       "anonCredsRevocationRegistryId": "M6dhuFj5UwbhWkSLmvYSPc:4:M6dhuFj5UwbhWkSLmvYSPc:3:CL:612088:student_card:CL_ACCUM:5f6b196c-2051-4c30-92e1-e22af703ba8f",
>       "anonCredsCredentialRevocationId": "13",
>       "connectionId": "90da9419-b550-4616-b087-0e48efd78b0d"
>     },
>     {
>       "anonCredsUnqualifiedRevocationRegistryId": "M6dhuFj5UwbhWkSLmvYSPc:4:M6dhuFj5UwbhWkSLmvYSPc:3:CL:612088:student_card:CL_ACCUM:5f6b196c-2051-4c30-92e1-e22af703ba8f",
>       "anonCredsCredentialRevocationId": "13",
>       "connectionId": "90da9419-b550-4616-b087-0e48efd78b0d"
>     }
>   ]
> ```
> 
> Not sure if I mentioned this already but it appears to be using the 'V1' revocation notification process, if that's helpful. Let me know what further info I could provide that might help.

Yeah the query parameters were mixed up in previous commit. Sad that once you updated the query it is still not finding any record. Looking [here](https://github.com/openwallet-foundation/credo-ts/blob/88767cf2667d683448cce0c302dc818c7ae11450/packages/anoncreds/src/utils/w3cAnonCredsUtils.ts#L202), it seems that Credo is not storing legacy identifiers because the issuer is not a qualified did:indy. I think this should be done **either** if it is a qualified or an unqualified did:indy. @auer-martin can you confirm?

File: packages/core/src/modules/credentials/protocol/revocation-notification/services/RevocationNotificationService.ts [hunk 1]
```diff
@@ -51,7 +51,21 @@ export class RevocationNotificationService {
     comment?: string
   ) {
     // TODO: can we extract support for this revocation notification handler to the anoncreds module?
-    const query = { anonCredsRevocationRegistryId, anonCredsCredentialRevocationId, connectionId: connection.id }
+    // Search for the revocation registry in both qualified and unqualified forms
+    const query = {
```
Comment (TimoGlastra) [inline packages/core/src/modules/credentials/protocol/revocation-notification/services/RevocationNotificationService.ts:55]: Do we already store it in both formats? We MIGHT have to query the credential itself first and based on that find the exchange record (as we definitely store both qualified and unqualified on the w3c record)

**Comment by auer-martin** [comment]
> > Still getting no records with the updated query. Here's what the query ends up looking like:
> > ```
> > "$or": [
> >     {
> >       "anonCredsRevocationRegistryId": "M6dhuFj5UwbhWkSLmvYSPc:4:M6dhuFj5UwbhWkSLmvYSPc:3:CL:612088:student_card:CL_ACCUM:5f6b196c-2051-4c30-92e1-e22af703ba8f",
> >       "anonCredsCredentialRevocationId": "14",
> >       "connectionId": "c8b60a89-4849-4697-9d8b-326e1f1ddc5c"
> >     },
> >     {
> >       "anonCredsRevocationRegistryId": "M6dhuFj5UwbhWkSLmvYSPc:4:M6dhuFj5UwbhWkSLmvYSPc:3:CL:612088:student_card:CL_ACCUM:5f6b196c-2051-4c30-92e1-e22af703ba8f",
> >       "anonCredsUnqualifiedRevocationRegistryId": "14",
> >       "connectionId": "c8b60a89-4849-4697-9d8b-326e1f1ddc5c"
> >     }
> >   ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I thought maybe the values passed were incorrect so I tried switching them, but still retrieved no records. Here's what that query looked like:
> > ```
> > "$or": [
> >     {
> >       "anonCredsRevocationRegistryId": "M6dhuFj5UwbhWkSLmvYSPc:4:M6dhuFj5UwbhWkSLmvYSPc:3:CL:612088:student_card:CL_ACCUM:5f6b196c-2051-4c30-92e1-e22af703ba8f",
> >       "anonCredsCredentialRevocationId": "13",
> >       "connectionId": "90da9419-b550-4616-b087-0e48efd78b0d"
> >     },
> >     {
> >       "anonCredsUnqualifiedRevocationRegistryId": "M6dhuFj5UwbhWkSLmvYSPc:4:M6dhuFj5UwbhWkSLmvYSPc:3:CL:612088:student_card:CL_ACCUM:5f6b196c-2051-4c30-92e1-e22af703ba8f",
> >       "anonCredsCredentialRevocationId": "13",
> >       "connectionId": "90da9419-b550-4616-b087-0e48efd78b0d"
> >     }
> >   ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Not sure if I mentioned this already but it appears to be using the 'V1' revocation notification process, if that's helpful. Let me know what further info I could provide that might help.
> 
> Yeah the query parameters were mixed up in previous commit. Sad that once you updated the query it is still not finding any record. Looking [here](https://github.com/openwallet-foundation/credo-ts/blob/88767cf2667d683448cce0c302dc818c7ae11450/packages/anoncreds/src/utils/w3cAnonCredsUtils.ts#L202), it seems that Credo is not storing legacy identifiers because the issuer is not a qualified did:indy. I think this should be done **either** if it is a qualified or an unqualified did:indy. @auer-martin can you confirm?

Yeah, I think that's a mistake.
I'm wondering if we should do it for qualified and unqualified Indy Dids, as we want to get rid of the unqualified variants eventually. But I don't think it will make a big difference if we do it for qualified and unqualified atm.

File: packages/core/src/modules/credentials/protocol/revocation-notification/services/RevocationNotificationService.ts (hunk 1 above)
Comment (genaris) [reply packages/core/src/modules/credentials/protocol/revocation-notification/services/RevocationNotificationService.ts:55]: I think the idea in 0.5 was to store both in the w3c record, but up to now it is doing so only in case the issuer is a qualified did:indy, which is not the case in BCGov demo for example, so unqualified form is not being recorded there.

But something I'm thinking while inspectic the code is the following: `LegacyIndyCredentialFormatService` is supposed to work only with unqualified identifiers, right? In that case, to fix this particular issue shouldn't it suffice to simply store `revocationRegistryId` tag and metadata in unqualified format?

Comment (TimoGlastra) [reply packages/core/src/modules/credentials/protocol/revocation-notification/services/RevocationNotificationService.ts:55]: > But something I'm thinking while inspectic the code is the following: LegacyIndyCredentialFormatService is supposed to work only with unqualified identifiers, right? In that case, to fix this particular issue shouldn't it suffice to simply store anonCredsRevocationRegistryId tag and metadata in unqualified format?

I think for the migration it's easier if we can store as much as possible as qualified identifiers. It's very simple to go from qualified -> unqualified, not the other way around. In the future it would be nice if you could send a revocation notification with a qualified identifier for a credential that was issued as unqualified.

**Comment by bryce-mcmath** [comment]
Just tried one of the approaches suggested; removing the  `(isIndyDid(issuerId)` from [here](https://github.com/openwallet-foundation/credo-ts/blob/88767cf2667d683448cce0c302dc818c7ae11450/packages/anoncreds/src/utils/w3cAnonCredsUtils.ts#L202), keeping the other change from this PR as well (or query).

It still unfortunately did not find the record, not sure why. Here's what my resulting `w3cRecordAnonCredsTags` looked like:
```
{
  "anonCredsLinkSecretId": "790feabb-8054-41c9-8df5-197e3f646979",
  "anonCredsCredentialDefinitionId": "did:indy:bcovrin:test:QEquAHkM35w4XVT3Ku5yat/anoncreds/v0/CLAIM_DEF/567943/student_card",
  "anonCredsSchemaId": "did:indy:bcovrin:test:QEquAHkM35w4XVT3Ku5yat/anoncreds/v0/SCHEMA/student_card/1.4",
  "anonCredsSchemaName": "student_card",
  "anonCredsSchemaIssuerId": "did:indy:bcovrin:test:QEquAHkM35w4XVT3Ku5yat",
  "anonCredsSchemaVersion": "1.4",
  "anonCredsMethodName": "indy",
  "anonCredsRevocationRegistryId": "did:indy:bcovrin:test:QEquAHkM35w4XVT3Ku5yat/anoncreds/v0/REV_REG_DEF/567943/student_card/ac6d918c-6532-45a8-b74c-4a2533e596a2",
  "anonCredsCredentialRevocationId": "1",
  "anonCredsUnqualifiedIssuerId": "QEquAHkM35w4XVT3Ku5yat",
  "anonCredsUnqualifiedCredentialDefinitionId": "QEquAHkM35w4XVT3Ku5yat:3:CL:567943:student_card",
  "anonCredsUnqualifiedSchemaId": "QEquAHkM35w4XVT3Ku5yat:2:student_card:1.4",
  "anonCredsUnqualifiedSchemaIssuerId": "QEquAHkM35w4XVT3Ku5yat",
  "anonCredsUnqualifiedRevocationRegistryId": "QEquAHkM35w4XVT3Ku5yat:4:QEquAHkM35w4XVT3Ku5yat:3:CL:567943:student_card:CL_ACCUM:ac6d918c-6532-45a8-b74c-4a2533e596a2"
}
```

and here's what my query looked like:
```
query: {
  "$or": [
    {
      "anonCredsRevocationRegistryId": "QEquAHkM35w4XVT3Ku5yat:4:QEquAHkM35w4XVT3Ku5yat:3:CL:567943:student_card:CL_ACCUM:ac6d918c-6532-45a8-b74c-4a2533e596a2",
      "anonCredsCredentialRevocationId": "1",
      "connectionId": "985d47bb-a7e7-4b1b-8ac8-02e407b5e0a1"
    },
    {
      "anonCredsUnqualifiedRevocationRegistryId": "QEquAHkM35w4XVT3Ku5yat:4:QEquAHkM35w4XVT3Ku5yat:3:CL:567943:student_card:CL_ACCUM:ac6d918c-6532-45a8-b74c-4a2533e596a2",
      "anonCredsCredentialRevocationId": "1",
      "connectionId": "985d47bb-a7e7-4b1b-8ac8-02e407b5e0a1"
    }
  ]
}
```

Let me know if anything here stands out.

**Comment by genaris** [comment]
> Just tried one of the approaches suggested; removing the `(isIndyDid(issuerId)` from [here](https://github.com/openwallet-foundation/credo-ts/blob/88767cf2667d683448cce0c302dc818c7ae11450/packages/anoncreds/src/utils/w3cAnonCredsUtils.ts#L202), keeping the other change from this PR as well (or query).
> 
> It still unfortunately did not find the record, not sure why. Here's what my resulting `w3cRecordAnonCredsTags` looked like:
> 
> Let me know if anything here stands out.

The issue is that in `RevocationNotificationService` we are looking at the tag in the CredentialExchangeRecord (i.e. the record holding the credential issuance flow) while these new unqualified tags are being stored into the CredentialRecord itself.

So for the moment I've updated `LegacyIndyCredentialFormatService` to set the unqualified identifier as a tag of the CredentialExchangeRecord (in addition to the qualified one), which seems to be working fine for BC Wallet showcase demo credentials.

File: packages/anoncreds/src/formats/LegacyIndyCredentialFormatService.ts [hunk 2]
```diff
@@ -399,6 +399,7 @@ export class LegacyIndyCredentialFormatService implements CredentialFormatServic
       })
       credentialRecord.setTags({
         anonCredsRevocationRegistryId: credential.revocationRegistryId,
+        anonCredsUnqualifiedRevocationRegistryId: anonCredsCredential.rev_reg_id,
```
Comment (bryce-mcmath) [inline packages/anoncreds/src/formats/LegacyIndyCredentialFormatService.ts:402]: Is this addition also needed in the `acceptRequest` method? (Line 277)

**Comment by bryce-mcmath** [comment]
I have one comment above just asking if we need an extra addition but as it is currently revocation works! Thank you all for your help this far

**Comment by bryce-mcmath** [comment]
Oh one other question. Will this only solve the problem for newly issued credentials, credentials issued with AFJ 0.4.2 will still fail revocation, no?

File: packages/anoncreds/src/formats/LegacyIndyCredentialFormatService.ts (hunk 2 above)
Comment (genaris) [reply packages/anoncreds/src/formats/LegacyIndyCredentialFormatService.ts:402]: That's for the issuer part, but yes, it should be added also here if we follow this approach.

**Comment by genaris** [comment]
> Oh one other question. Will this only solve the problem for newly issued credentials, credentials issued with AFJ 0.4.2 will still fail revocation, no?

From my understanding, credentials issued with 0.4.2 should work, since at the moment we are not touching any tag in CredentialExchangeRecord during record migration. So I guess it will have `anonCredsRevocationRegistryId: "QEquAHkM35w4XVT3Ku5yat:4:QEquAHkM35w4XVT3Ku5yat:3:CL:567943:student_card:CL_ACCUM:ac6d918c-6532-45a8-b74c-4a2533e596a2"` (i.e. the unqualified one, matching what you are sending to it).

BTW for consistency, I think if we follow this `anonCredsUnqualifiedRevocationRegistryId` approach, it will be nice to also create this tag in the migration scripts.

**Comment by bryce-mcmath** [comment]
> From my understanding, credentials issued with 0.4.2 should work, since at the moment we are not touching any tag in CredentialExchangeRecord during record migration

I can confirm that revocation in 0.5.2 for credentials issued in 0.4.2 work with these changes.

File: packages/anoncreds/src/formats/LegacyIndyCredentialFormatService.ts [hunk 3]
```diff
@@ -300,23 +300,12 @@ export class LegacyIndyCredentialFormatService implements CredentialFormatServic
...
     if (!credentialRequest) throw new CredoError('Missing indy credential request in createCredential')
 
-    const { credential, credentialRevocationId } = await anonCredsIssuerService.createCredential(agentContext, {
+    const { credential } = await anonCredsIssuerService.createCredential(agentContext, {
       credentialOffer,
       credentialRequest,
       credentialValues: convertAttributesToCredentialValues(credentialAttributes),
     })
 
-    if (credential.rev_reg_id) {
```
Comment (genaris) [inline packages/anoncreds/src/formats/LegacyIndyCredentialFormatService.ts:309]: I removed it from here because we don't actually support revocation with legacy indy credentials (but we do in AnonCreds, so tags are added to issued credentials there)

Comment (TimoGlastra) [reply packages/anoncreds/src/formats/LegacyIndyCredentialFormatService.ts:309]: WDYM? A credential with legacy identifiers can't use revocation? Is that because it's not implemented in the legacy credential format service?

**Review by TimoGlastra — APPROVED** [review]
It looks good 👍  but it's also complex logic with all this qualified vs unqualified so I might miss things 😅

File: packages/anoncreds/src/formats/LegacyIndyCredentialFormatService.ts (hunk 3 above)
Comment (genaris) [reply packages/anoncreds/src/formats/LegacyIndyCredentialFormatService.ts:309]: Yes, we do not currently support issuing revocable legacy indy credentials, so I don't see how this if statement can be true.

File: packages/anoncreds/src/updates/0.4-0.5/anonCredsCredentialRecord.ts [hunk 4]
```diff
@@ -154,6 +155,16 @@ async function migrateLegacyToW3cCredential(agentContext: AgentContext, legacyRe
         credentialRecordType: 'w3c',
         credentialRecordId: w3cCredentialRecord.id,
       }
+
+      // If using unqualified dids, store both qualified/unqualified revRegId forms
+      // to allow retrieving it from revocation notification service
+      if (qualifiedRevocationRegistryId && indyNamespace) {
```
[the remark this answers is not in the document]
Comment (genaris) [reply packages/anoncreds/src/updates/0.4-0.5/anonCredsCredentialRecord.ts:161]: It was mostly to optimize a bit the code but I'll change it, since it is not clear

File: packages/anoncreds/src/utils/w3cAnonCredsUtils.ts [hunk 5]
```diff
@@ -199,7 +200,7 @@ export function getW3cRecordAnonCredsTags(options: {
     anonCredsMethodName: methodName,
     anonCredsRevocationRegistryId: revocationRegistryId,
     anonCredsCredentialRevocationId: credentialRevocationId,
-    ...(isIndyDid(issuerId) && {
+    ...((isIndyDid(issuerId) || isUnqualifiedIndyDid(issuerId)) && {
```
[the remark this answers is not in the document]
Comment (genaris) [reply packages/anoncreds/src/utils/w3cAnonCredsUtils.ts:203]: I've understood from a previous comment that it was better to store the qualified form because it was not possible to go the other way around. Now I'm confused!

File: packages/anoncreds/src/formats/LegacyIndyCredentialFormatService.ts (hunk 3 above)
Comment (cvarjao) [reply packages/anoncreds/src/formats/LegacyIndyCredentialFormatService.ts:309]: what do you mean by "legacy indy credentials"? is there a short documentation about what is considered legacy?

Comment (bryce-mcmath) [reply packages/anoncreds/src/formats/LegacyIndyCredentialFormatService.ts:309]: @genaris I know this is already merged but could I get a bit of clarification here; is this method only for *issuing credentials*? The name `acceptRequest` implies it could be accepting a credential issued by another agent that does support issuing legacy creds, no? Currently our ecosystem uses revocation with credentials that don't start with `did:indy` etc. ie. "legacy" credentials as I understand it, so it seems like we would need to keep this `if` block. Let me know what you think

Comment (genaris) [reply packages/anoncreds/src/formats/LegacyIndyCredentialFormatService.ts:309]: The naming here is mainly based on DIDComm Issue Credential protocols, where the steps are propose -> offer -> request -> issue (see [here](https://github.com/hyperledger/aries-rfcs/blob/main/features/0453-issue-credential-v2/README.md#messages)). This `acceptRequest` is about responding to the `request-credential` message, sent from the holder to the issuer to ask for the actual credential issuance.

So this method is only called in issuer use case. As you can see some lines before, we are calling `anoncredsIssuerService.createCredential` without any revocation-related `CreateCredentialOptions` parameter (revocationRegistryDefinitionId, revocationRegistryIndex, revocationStatusList), like we do in [AnonCredsCredentialFormatService](https://github.com/openwallet-foundation/credo-ts/blob/dcb363dc7e7abbbcce8b3a344a487a186eb5c88e/packages/anoncreds/src/formats/AnonCredsCredentialFormatService.ts#L344).

Comment (bryce-mcmath) [reply packages/anoncreds/src/formats/LegacyIndyCredentialFormatService.ts:309]: Ah, ok. Got it. Thank you!

**Comment by bryce-mcmath** [comment]
> could we also do this for credentials and proofs?

@wadeking98 do you still want this? @genaris see any issue doing this?
