### PR TITLE
fix: Revocation Index 0 anoncreds-rs support

### LINKED ISSUE #2125: bug: anoncreds-rs issuance of revocation index 0 silently issues non-revokable cred
I was finding that when i issued a revocable cred with index 0, the issued credential would be issued without any attachment to a revocation registry (non-revocable). e.g.:
```ts
  const credEx = await credentials.offerCredential({
    protocolVersion: "v2",
    connectionId: connId,
    credentialFormats: {
      anoncreds: {
        credentialDefinitionId: credDefId,
        attributes: [
          { name: "name", value: "Jane Doe" },
          { name: "age", value: "23" },
        ],
        revocationRegistryIndex: 0,
        revocationRegistryDefinitionId: revRegDefId,
      },
    },
  });
```

I believe this is because the anoncreds-rs issuer service only assembles `CredentialRevocationConfig` if `revocationRegistryIndex` is truthy - so it skips `CredentialRevocationConfig` construction if `revocationRegistryIndex` is `0`. Problem resolved when i moved to index `1`

https://github.com/openwallet-foundation/credo-ts/blob/9d934afc87eb7dad87fd65681ada4df0333bd439/packages/anoncreds/src/anoncreds-rs/AnonCredsRsIssuerService.ts#L323

### PR DESCRIPTION
**Pull request by gmulhearn**
Closes #2125

### CODE REVIEW

File: packages/anoncreds/src/anoncreds-rs/AnonCredsRsIssuerService.ts [hunk 1]
```diff
@@ -320,7 +320,7 @@ export class AnonCredsRsIssuerService implements AnonCredsIssuerService {
       }
 
       let revocationConfiguration: CredentialRevocationConfig | undefined
-      if (revocationRegistryDefinitionId && revocationStatusList && revocationRegistryIndex) {
+      if (revocationRegistryDefinitionId && revocationStatusList && revocationRegistryIndex !== undefined) {
```
Comment (TimoGlastra) [inline packages/anoncreds/src/anoncreds-rs/AnonCredsRsIssuerService.ts:323]: I just remembered it starts at one by convetion, so it will still throw later on i think. But this at least fixes your issue. 

We might want to add an error saying index 0 is not allowed?

https://github.com/hyperledger/anoncreds-rs/issues/337

**Review by TimoGlastra — APPROVED** [review]

File: packages/anoncreds/src/anoncreds-rs/AnonCredsRsIssuerService.ts (hunk 1 above)
Comment (gmulhearn) [reply packages/anoncreds/src/anoncreds-rs/AnonCredsRsIssuerService.ts:323]: oh damn! i didn't know this. i guess atleast with this change it will make it's way down into anoncreds-rs, where it will then throw an error - rather than current behaviour where it silently becomes non-revokable.

FYI i just tried running this fix with an index 0 input. i get the error:
```
AnoncredsError: Invalid state: Revocation index is outside of valid range
```

**Comment by gmulhearn** [comment]
I'm getting the same int test failure on my other PR: https://github.com/openwallet-foundation/credo-ts/pull/2124 . 

seems unrelated?

File: packages/anoncreds/src/anoncreds-rs/AnonCredsRsIssuerService.ts (hunk 1 above)
Comment (TimoGlastra) [reply packages/anoncreds/src/anoncreds-rs/AnonCredsRsIssuerService.ts:323]: okay then let's merge this, because it improves a lot

**Comment by TimoGlastra** [comment]
> I'm getting the same int test failure on my other PR: #2124 .
> 
> seems unrelated?

YEs we need to fix the CI, if it's only the unrelated issue i can merge it!

File: packages/anoncreds/src/anoncreds-rs/AnonCredsRsIssuerService.ts (hunk 1 above)
Comment (genaris) [reply packages/anoncreds/src/anoncreds-rs/AnonCredsRsIssuerService.ts:323]: I'm a bit late into the conversation but yes, this came originally from the fact that an index = 0 is not allowed. 

I think it would be great if you can add an specific check for `revocationRegistryIndex === 0` with an appropriate error message, since this is confusing for those who are not familiar with this convention (which BTW is only shyly mentioned in the [spec](https://hyperledger.github.io/anoncreds-spec/): _"Each credential issued using the Revocation Registry is given its own index (1 to the capacity of the Revocation Registry into the array, the index of the point for that credential."_)
